# Example decisions.toml with full dependency schema
# This shows all available fields and patterns

[metadata]
version = "1.0"
description = "Technical decisions for the project"
createdAt = "2025-01-01"

[defaults]
reviewAfter = "6m"

# Global dependency rules
[rules.deps]
maxAge = 30               # days before review required
oldReason = true          # require reason for outdated deps  
checkInterval = 7         # days between update checks
autoPatches = true        # allow automated patch updates
blockMajor = true         # block major updates without review

[rules.deps.tiers]
essential.review = 90     # review cycle in days
essential.altRequired = true
justified.review = 30
justified.triggerRequired = true
deprecated.review = 14
deprecated.planRequired = true

# Dependencies with rich metadata
[dependencies.typescript]
decision = "keep"
current = "^5.0.0"
available = "^5.3.0"
reason = "Essential for type safety"
reviewBy = "2025-08-27"
tier = "essential"

  [dependencies.typescript.policy]
  update = "manual"       # Never auto-update compiler
  major = "block"         # Major versions need careful review
  range = "^"            # Use caret for minor updates

  [dependencies.typescript.meta]
  security = "critical"   # Compiler is security-critical
  alt = "JavaScript (rejected: no type safety)"

[dependencies."@types/node"]
decision = "keep"
current = "^20.0.0"
available = "^20.11.0"
reason = "Type definitions, safe to auto-update"
reviewBy = "2025-06-01"
tier = "essential"

  [dependencies."@types/node".policy]
  update = "auto"         # Auto-update patches and minors
  range = "^"
  major = "review"        # Review major versions

  [dependencies."@types/node".meta]
  security = "low"        # Just type definitions
  alt = "None suitable"

[dependencies.lodash]
decision = "deprecate"
current = "^4.17.21"
reason = "Moving to native JS methods"
reviewBy = "2025-01-15"
tier = "deprecated"

  [dependencies.lodash.meta]
  migrate = "docs/lodash-migration.md"

[dependencies.eslint-plugin-react]
decision = "keep"
current = "^7.33.0"
available = "^7.35.0"
reason = "React linting rules"
reviewBy = "2025-03-01"
tier = "justified"

  [dependencies.eslint-plugin-react.policy]
  update = "tagged"
  tag = "latest"          # Follow latest tag

  [dependencies.eslint-plugin-react.meta]
  trigger = "When we stop using React"
  peers = ["eslint@^8.0.0", "react@^18.0.0"]

# Other technical decisions
[architecture.monorepo]
value = "pnpm workspaces"
reason = "Native monorepo support with strict dependency management"
reviewBy = "2026-01-01"

[patterns.imports]
value = "ESM with .ts extensions"
reason = "Native TypeScript support in Node.js 22+"
reviewBy = "2025-12-01"